os: linux
variables:
  JBAKE_VERSION: 2.6.3
addons:
  apt:
    packages:
      - lftp
sudo: false
jdk:
  - openjdk8
branches:
  only:
    - master
before_install:
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install jbake $JBAKE_VERSION < /dev/null
  - sdk use jbake $JBAKE_VERSION
  - chmod +x scripts/travis_build
script: scripts/travis_build
notifications:
  email:
    on_success: change # default: change
on_failure: always # default: always
